<a href="https://colab.research.google.com/github/vardhanreddy2003/GPT-2Training/blob/main/MaskedSelfAttention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
inputs=torch.rand(512,64)

In [ ]:
inputs.shape

torch.Size([512, 64])

In [ ]:
query_m=torch.rand(64,64)
key_m=torch.rand(64,64)
value_m=torch.rand(64,64)

In [ ]:
query_i=inputs@query_m
key_i=inputs@key_m
value_i=inputs@value_m
print(query_i.shape)

torch.Size([512, 64])


In [ ]:
attn_scores=(query_i.T@key_i)
attn_scores.shape

torch.Size([64, 64])

In [ ]:
attn_scores

tensor([[130444.5547, 138133.0469, 131787.6719,  ..., 136132.6875,
         140070.0469, 107100.6875],
        [130042.5000, 137708.1250, 131325.3125,  ..., 135785.6094,
         139600.3906, 106740.4141],
        [150633.4062, 159586.5000, 152257.9844,  ..., 157346.1250,
         161805.0469, 123808.8828],
        ...,
        [132960.7656, 140905.0469, 134335.6094,  ..., 138828.0000,
         142825.8750, 109213.3281],
        [120901.2578, 128128.0234, 122161.4844,  ..., 126217.2812,
         129794.6875,  99335.7266],
        [135533.9688, 143615.3438, 136955.5625,  ..., 141579.3281,
         145647.1719, 111346.9219]])

In [ ]:
attn_weights=attn_scores/(inputs.shape[-1]**0.5)
attn_weights.shape

torch.Size([64, 64])

In [ ]:
context_values=attn_weights@value_i.T
context_values=context_values.T
context_values.shape

torch.Size([512, 64])

In [ ]:
torch.ones(context_values[0].shape[0], 64)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [ ]:
mask_simple=torch.tril(torch.ones(64,64))
mask_simple

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 1., 0., 0.],
        [1., 1., 1.,  ..., 1., 1., 0.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [ ]:
masked_attention=attn_weights*mask_simple
masked_attention

tensor([[16305.5693,     0.0000,     0.0000,  ...,     0.0000,     0.0000,
             0.0000],
        [16255.3125, 17213.5156,     0.0000,  ...,     0.0000,     0.0000,
             0.0000],
        [18829.1758, 19948.3125, 19032.2480,  ...,     0.0000,     0.0000,
             0.0000],
        ...,
        [16620.0957, 17613.1309, 16791.9512,  ..., 17353.5000,     0.0000,
             0.0000],
        [15112.6572, 16016.0029, 15270.1855,  ..., 15777.1602, 16224.3359,
             0.0000],
        [16941.7461, 17951.9180, 17119.4453,  ..., 17697.4160, 18205.8965,
         13918.3652]])

In [ ]:
row_sums=masked_attention.sum(dim=1,keepdim=True)
masked_attention_norm=masked_attention/row_sums
masked_attention_norm

tensor([[1.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.4857, 0.5143, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.3257, 0.3451, 0.3292,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0157, 0.0166, 0.0158,  ..., 0.0164, 0.0000, 0.0000],
        [0.0154, 0.0163, 0.0156,  ..., 0.0161, 0.0165, 0.0000],
        [0.0152, 0.0161, 0.0154,  ..., 0.0159, 0.0164, 0.0125]])

Note:You can't substitute 0 in upper triangular matrix because its exponent value will not become 0 during softmax.So,we use -infinite so when we do softmax its value gets 0.


In [ ]:
mask=torch.triu(torch.ones(64,64),diagonal=1)
print(mask)

tensor([[0., 1., 1.,  ..., 1., 1., 1.],
        [0., 0., 1.,  ..., 1., 1., 1.],
        [0., 0., 0.,  ..., 1., 1., 1.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [ ]:
attn_weights

tensor([[16305.5693, 17266.6309, 16473.4590,  ..., 17016.5859, 17508.7559,
         13387.5859],
        [16255.3125, 17213.5156, 16415.6641,  ..., 16973.2012, 17450.0488,
         13342.5518],
        [18829.1758, 19948.3125, 19032.2480,  ..., 19668.2656, 20225.6309,
         15476.1104],
        ...,
        [16620.0957, 17613.1309, 16791.9512,  ..., 17353.5000, 17853.2344,
         13651.6660],
        [15112.6572, 16016.0029, 15270.1855,  ..., 15777.1602, 16224.3359,
         12416.9658],
        [16941.7461, 17951.9180, 17119.4453,  ..., 17697.4160, 18205.8965,
         13918.3652]])

In [ ]:
masked_attn_weights=attn_weights.masked_fill(mask.bool(),-torch.inf)
print(masked_attn_weights)

tensor([[16305.5693,       -inf,       -inf,  ...,       -inf,       -inf,
               -inf],
        [16255.3125, 17213.5156,       -inf,  ...,       -inf,       -inf,
               -inf],
        [18829.1758, 19948.3125, 19032.2480,  ...,       -inf,       -inf,
               -inf],
        ...,
        [16620.0957, 17613.1309, 16791.9512,  ..., 17353.5000,       -inf,
               -inf],
        [15112.6572, 16016.0029, 15270.1855,  ..., 15777.1602, 16224.3359,
               -inf],
        [16941.7461, 17951.9180, 17119.4453,  ..., 17697.4160, 18205.8965,
         13918.3652]])


In [ ]:
at= torch.softmax(masked_attn_weights,dim=1)
print(at)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


Note :The values that I have taken are very large so softmax results are not that efficient


In [ ]:
inputs.shape

torch.Size([512, 64])

In [ ]:
import torch.nn as nn

In [ ]:
d_in=64
d_out=64
query_w=nn.Linear(d_in,d_out,bias=False)
key_w=nn.Linear(d_in,d_out,bias=False)
value_w=nn.Linear(d_in,d_out,bias=False)

In [ ]:
queries=query_w(inputs)
keys=key_w(inputs)
values=value_w(inputs)

In [ ]:
print(queries.shape)
print(keys.shape)

torch.Size([512, 64])
torch.Size([512, 64])


In [ ]:
attn_scores=queries@keys.T
attn_scores.shape

torch.Size([512, 512])

In [ ]:
va=attn_scores@values

In [ ]:
va.shape

torch.Size([512, 64])

In [ ]:
attn_weights=torch.softmax(attn_scores/keys.shape[-1]**0.5,dim=-1)

In [ ]:
attn_weights[0]

tensor([0.0018, 0.0020, 0.0020, 0.0020, 0.0020, 0.0019, 0.0019, 0.0020, 0.0021,
        0.0019, 0.0020, 0.0022, 0.0020, 0.0019, 0.0019, 0.0019, 0.0019, 0.0019,
        0.0021, 0.0021, 0.0018, 0.0018, 0.0020, 0.0019, 0.0019, 0.0018, 0.0018,
        0.0019, 0.0020, 0.0019, 0.0021, 0.0021, 0.0018, 0.0019, 0.0021, 0.0020,
        0.0019, 0.0020, 0.0019, 0.0019, 0.0019, 0.0019, 0.0020, 0.0020, 0.0020,
        0.0020, 0.0020, 0.0017, 0.0019, 0.0018, 0.0020, 0.0019, 0.0020, 0.0020,
        0.0020, 0.0020, 0.0019, 0.0020, 0.0020, 0.0020, 0.0020, 0.0020, 0.0020,
        0.0019, 0.0020, 0.0020, 0.0020, 0.0020, 0.0021, 0.0019, 0.0018, 0.0020,
        0.0020, 0.0020, 0.0019, 0.0018, 0.0019, 0.0020, 0.0019, 0.0018, 0.0019,
        0.0018, 0.0019, 0.0019, 0.0020, 0.0019, 0.0018, 0.0020, 0.0020, 0.0020,
        0.0019, 0.0020, 0.0019, 0.0020, 0.0021, 0.0021, 0.0020, 0.0020, 0.0020,
        0.0019, 0.0020, 0.0021, 0.0020, 0.0019, 0.0020, 0.0019, 0.0018, 0.0019,
        0.0019, 0.0020, 0.0020, 0.0021, 

In [ ]:
context_values=attn_weights@values
context_values.shape

torch.Size([512, 64])

In [ ]:
class SelfAttention(nn.Module):
  def __init__(self,d_in,d_out) -> None:
    super().__init__()
    self.query_w=nn.Linear(d_in,d_out,bias=False)
    self.key_w=nn.Linear(d_in,d_out,bias=False)
    self.value_w=nn.Linear(d_in,d_out,bias=False)

  def forward(self,inputs):
    queries=self.query_w(inputs)
    keys=self.key_w(inputs)
    values=self.value_w(inputs)

    attn_scores=queries@keys.T
    attn_weights=torch.softmax(attn_scores/keys.shape[-1]**0.5,dim=-1)
    context_values=attn_weights@values
    return context_values

In [ ]:
sa=SelfAttention(d_in=64,d_out=64)
print(sa(inputs).shape)

torch.Size([512, 64])


In [ ]:
mask=torch.triu(torch.ones(d_in,d_out),diagonal=1)
print(mask)

tensor([[0., 1., 1.,  ..., 1., 1., 1.],
        [0., 0., 1.,  ..., 1., 1., 1.],
        [0., 0., 0.,  ..., 1., 1., 1.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [ ]:
class MaskedSelfAttention(nn.Module):
  def __init__(self,d_in,d_out) -> None:
    super().__init__()
    self.query_w=nn.Linear(d_in,d_out,bias=False)
    self.key_w=nn.Linear(d_in,d_out,bias=False)
    self.value_w=nn.Linear(d_in,d_out,bias=False)

  def forward(self,inputs):
    queries=self.query_w(inputs)
    keys=self.key_w(inputs)
    values=self.value_w(inputs)

    attn_scores=queries@keys.T
    mask=torch.triu(torch.ones(inputs.shape[0],inputs.shape[0]),diagonal=1)
    attn_scores=attn_scores.masked_fill(mask.bool(),-torch.inf)
    attn_weights=torch.softmax(attn_scores/keys.shape[-1]**0.5,dim=1)
    context_values=attn_weights@values
    return context_values

In [ ]:
sa=MaskedSelfAttention(d_in=64,d_out=64)
print(sa(inputs).shape)


torch.Size([512, 64])
